services:

  app:
    restart: unless-stopped
    image: node:24
    user: node
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - BITBANK_API_KEY=${BITBANK_API_KEY}
      - BITBANK_API_SECRET=${BITBANK_API_SECRET}
      - BITBANK_ACCESS_TIME_WINDOW_MS=${BITBANK_ACCESS_TIME_WINDOW_MS:-5000}
    init: true
    working_dir: /app
    depends_on:
      - postgres
    command: sleep infinity
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    networks:
      - default

  postgres:
    restart: unless-stopped
    image: postgres:18
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default
      - grafana

volumes:
  pg-data:
  app_node_modules:

networks:
  grafana:
    name: grafana
    external: true
